(async () => {
  const dictionaries = {
    fr: {
      "Prepare images locally. Nothing is uploaded.": "Préparez vos images localement. Aucun envoi en ligne.", "Settings": "Paramètres", "Start over": "Recommencer",
      "Drop an image here": "Déposez une image ici", "Choose an image": "Choisir une image", "Paste from clipboard": "Coller depuis le presse-papiers", "Image selected from the page": "Image sélectionnée sur la page", "Allow and import": "Autoriser et importer", "Processing stays in this browser. EXIF metadata is removed when exporting.": "Le traitement reste dans ce navigateur. Les métadonnées EXIF sont supprimées à l’export.",
      "Show original": "Voir l’original", "Replace": "Remplacer", "Original": "Original", "Output": "Résultat", "Drag the image to choose the crop.": "Faites glisser l’image pour choisir le recadrage.", "Batch queue": "File d’attente", "Process and download all": "Traiter et télécharger tout",
      "Required format": "Format requis", "For forms and websites": "Pour formulaires et sites web", "Small photos": "Photos légères", "Transparency": "Transparence", "For developers": "Pour développeurs", "Smallest files": "Fichiers les plus légers",
      "Dimensions": "Dimensions", "Lock ratio": "Conserver le ratio", "Preset": "Préréglage", "Original dimensions": "Dimensions d’origine", "Custom dimensions": "Dimensions personnalisées", "Width": "Largeur", "Height": "Hauteur", "Fit": "Ajuster", "Fill & crop": "Remplir et recadrer", "Stretch": "Étirer",
      "Background & transparency": "Fond et transparence", "Canvas background": "Fond de l’image", "Transparent (PNG/WebP)": "Transparent (PNG/WebP)", "White": "Blanc", "Custom color": "Couleur personnalisée", "Make a solid background transparent": "Rendre un fond uni transparent", "Best for logos and product images on a plain background.": "Idéal pour les logos et produits sur fond uni.", "Tolerance": "Tolérance", "Lower values preserve more edge detail.": "Une valeur faible préserve mieux les contours.",
      "Quality & maximum size": "Qualité et poids maximal", "Quality": "Qualité", "Maximum file size": "Poids maximal", "Optional": "Facultatif", "Exact size": "Dimensions exactes", "Never reduce dimensions": "Ne jamais réduire les dimensions", "No limit": "Sans limite", "Add a limit when a form imposes a maximum file size.": "Ajoutez une limite lorsqu’un formulaire impose un poids maximal.",
      "Filename": "Nom du fichier", "Download optimized image": "Télécharger l’image optimisée", "Settings save automatically.": "Les paramètres sont enregistrés automatiquement.", "Default format": "Format par défaut", "Quality defaults": "Qualité par défaut", "Context menu & filenames": "Menu contextuel et noms", "Privacy": "Confidentialité", "Local history": "Historique local", "Backup & restore": "Sauvegarde et restauration", "Export settings": "Exporter les paramètres", "Import settings": "Importer les paramètres", "Clear history": "Effacer l’historique", "Close settings": "Fermer les paramètres", "About & support": "À propos et assistance", "FormPix Studio is designed and developed by Stéphane Dinahet.": "FormPix Studio est conçu et développé par Stéphane Dinahet.", "View SDINAHET on GitHub ↗": "Voir SDINAHET sur GitHub ↗", "Rate the extension": "Noter l’extension", "Send feedback": "Envoyer un avis", "Get assistance": "Obtenir de l’aide", "Share FormPix Studio": "Partager FormPix Studio", "Rating and sharing links become active after publication on the Chrome Web Store.": "Les liens de notation et de partage deviennent actifs après la publication sur le Chrome Web Store.", "Open ↗": "Ouvrir ↗", "Unavailable": "Indisponible", "Interface language": "Langue de l’interface", "Language": "Langue", "Browser default": "Langue du navigateur", "Back": "Retour", "Back to FormPix Studio": "Retour à FormPix Studio", "Website image access": "Accès aux images des sites", "Allow once for all websites": "Autoriser une fois pour tous les sites", "Chrome asks once, then imports automatically everywhere.": "Chrome demande une seule fois, puis importe automatiquement partout.", "Ask for each new website": "Demander pour chaque nouveau site", "Permission is remembered for that domain.": "L’autorisation est mémorisée pour ce domaine."
    },
    es: {
      "Prepare images locally. Nothing is uploaded.": "Prepara imágenes localmente. No se sube nada.", "Settings": "Ajustes", "Start over": "Empezar de nuevo", "Drop an image here": "Suelta una imagen aquí", "Choose an image": "Elegir una imagen", "Paste from clipboard": "Pegar desde el portapapeles", "Allow and import": "Permitir e importar", "Show original": "Ver original", "Replace": "Reemplazar", "Original": "Original", "Output": "Resultado", "Batch queue": "Cola por lotes", "Process and download all": "Procesar y descargar todo", "Required format": "Formato requerido", "For forms and websites": "Para formularios y sitios web", "Dimensions": "Dimensiones", "Lock ratio": "Bloquear proporción", "Preset": "Preajuste", "Width": "Ancho", "Height": "Alto", "Fit": "Ajustar", "Fill & crop": "Rellenar y recortar", "Stretch": "Estirar", "Background & transparency": "Fondo y transparencia", "White": "Blanco", "Custom color": "Color personalizado", "Tolerance": "Tolerancia", "Quality & maximum size": "Calidad y tamaño máximo", "Quality": "Calidad", "Maximum file size": "Tamaño máximo", "Optional": "Opcional", "Exact size": "Tamaño exacto", "No limit": "Sin límite", "Filename": "Nombre de archivo", "Download optimized image": "Descargar imagen optimizada", "Privacy": "Privacidad", "Local history": "Historial local", "Backup & restore": "Copia y restauración", "Export settings": "Exportar ajustes", "Import settings": "Importar ajustes", "Clear history": "Borrar historial", "Close settings": "Cerrar ajustes"
    },
    de: {
      "Prepare images locally. Nothing is uploaded.": "Bilder lokal vorbereiten. Nichts wird hochgeladen.", "Settings": "Einstellungen", "Start over": "Neu beginnen", "Drop an image here": "Bild hier ablegen", "Choose an image": "Bild auswählen", "Paste from clipboard": "Aus Zwischenablage einfügen", "Allow and import": "Erlauben und importieren", "Show original": "Original anzeigen", "Replace": "Ersetzen", "Original": "Original", "Output": "Ergebnis", "Batch queue": "Stapelverarbeitung", "Process and download all": "Alle verarbeiten und herunterladen", "Required format": "Benötigtes Format", "Dimensions": "Abmessungen", "Lock ratio": "Seitenverhältnis sperren", "Preset": "Voreinstellung", "Width": "Breite", "Height": "Höhe", "Fit": "Einpassen", "Fill & crop": "Füllen und zuschneiden", "Stretch": "Strecken", "Background & transparency": "Hintergrund und Transparenz", "White": "Weiß", "Custom color": "Eigene Farbe", "Tolerance": "Toleranz", "Quality & maximum size": "Qualität und maximale Größe", "Quality": "Qualität", "Maximum file size": "Maximale Dateigröße", "Optional": "Optional", "Exact size": "Exakte Größe", "No limit": "Kein Limit", "Filename": "Dateiname", "Download optimized image": "Optimiertes Bild herunterladen", "Privacy": "Datenschutz", "Local history": "Lokaler Verlauf", "Backup & restore": "Sichern und Wiederherstellen", "Export settings": "Einstellungen exportieren", "Import settings": "Einstellungen importieren", "Clear history": "Verlauf löschen", "Close settings": "Einstellungen schließen"
    },
    pt_BR: {
      "Prepare images locally. Nothing is uploaded.": "Prepare imagens localmente. Nada é enviado.", "Settings": "Configurações", "Start over": "Recomeçar", "Drop an image here": "Solte uma imagem aqui", "Choose an image": "Escolher imagem", "Paste from clipboard": "Colar da área de transferência", "Allow and import": "Permitir e importar", "Show original": "Ver original", "Replace": "Substituir", "Original": "Original", "Output": "Resultado", "Batch queue": "Fila em lote", "Process and download all": "Processar e baixar tudo", "Required format": "Formato necessário", "Dimensions": "Dimensões", "Lock ratio": "Bloquear proporção", "Preset": "Predefinição", "Width": "Largura", "Height": "Altura", "Fit": "Ajustar", "Fill & crop": "Preencher e recortar", "Stretch": "Esticar", "Background & transparency": "Fundo e transparência", "White": "Branco", "Custom color": "Cor personalizada", "Tolerance": "Tolerância", "Quality & maximum size": "Qualidade e tamanho máximo", "Quality": "Qualidade", "Maximum file size": "Tamanho máximo", "Optional": "Opcional", "Exact size": "Tamanho exato", "No limit": "Sem limite", "Filename": "Nome do arquivo", "Download optimized image": "Baixar imagem otimizada", "Privacy": "Privacidade", "Local history": "Histórico local", "Backup & restore": "Backup e restauração", "Export settings": "Exportar configurações", "Import settings": "Importar configurações", "Clear history": "Limpar histórico", "Close settings": "Fechar configurações"
    },
    it: {
      "Prepare images locally. Nothing is uploaded.": "Prepara le immagini localmente. Nulla viene caricato.", "Settings": "Impostazioni", "Start over": "Ricomincia", "Drop an image here": "Trascina qui un’immagine", "Choose an image": "Scegli un’immagine", "Paste from clipboard": "Incolla dagli appunti", "Allow and import": "Consenti e importa", "Show original": "Mostra originale", "Replace": "Sostituisci", "Original": "Originale", "Output": "Risultato", "Batch queue": "Coda batch", "Process and download all": "Elabora e scarica tutto", "Required format": "Formato richiesto", "Dimensions": "Dimensioni", "Lock ratio": "Blocca proporzioni", "Preset": "Preimpostazione", "Width": "Larghezza", "Height": "Altezza", "Fit": "Adatta", "Fill & crop": "Riempi e ritaglia", "Stretch": "Allunga", "Background & transparency": "Sfondo e trasparenza", "White": "Bianco", "Custom color": "Colore personalizzato", "Tolerance": "Tolleranza", "Quality & maximum size": "Qualità e dimensione massima", "Quality": "Qualità", "Maximum file size": "Dimensione massima", "Optional": "Facoltativo", "Exact size": "Dimensioni esatte", "No limit": "Nessun limite", "Filename": "Nome file", "Download optimized image": "Scarica immagine ottimizzata", "Privacy": "Privacy", "Local history": "Cronologia locale", "Backup & restore": "Backup e ripristino", "Export settings": "Esporta impostazioni", "Import settings": "Importa impostazioni", "Clear history": "Cancella cronologia", "Close settings": "Chiudi impostazioni"
    },
    nl: { "Settings":"Instellingen", "Start over":"Opnieuw beginnen", "Drop an image here":"Sleep hier een afbeelding", "Choose an image":"Afbeelding kiezen", "Paste from clipboard":"Plakken vanaf klembord", "Show original":"Origineel tonen", "Replace":"Vervangen", "Output":"Resultaat", "Required format":"Vereist formaat", "Dimensions":"Afmetingen", "Width":"Breedte", "Height":"Hoogte", "Fit":"Passend", "Background & transparency":"Achtergrond en transparantie", "Quality":"Kwaliteit", "Maximum file size":"Maximale bestandsgrootte", "Filename":"Bestandsnaam", "Download optimized image":"Geoptimaliseerde afbeelding downloaden", "Privacy":"Privacy", "Local history":"Lokale geschiedenis", "Interface language":"Interfacetaal", "Language":"Taal", "Browser default":"Browserstandaard", "Back":"Terug" },
    pl: { "Settings":"Ustawienia", "Start over":"Zacznij od nowa", "Drop an image here":"Upuść obraz tutaj", "Choose an image":"Wybierz obraz", "Paste from clipboard":"Wklej ze schowka", "Show original":"Pokaż oryginał", "Replace":"Zastąp", "Output":"Wynik", "Required format":"Wymagany format", "Dimensions":"Wymiary", "Width":"Szerokość", "Height":"Wysokość", "Fit":"Dopasuj", "Background & transparency":"Tło i przezroczystość", "Quality":"Jakość", "Maximum file size":"Maksymalny rozmiar pliku", "Filename":"Nazwa pliku", "Download optimized image":"Pobierz zoptymalizowany obraz", "Privacy":"Prywatność", "Local history":"Historia lokalna", "Interface language":"Język interfejsu", "Language":"Język", "Browser default":"Domyślny przeglądarki", "Back":"Wstecz" },
    sv: { "Settings":"Inställningar", "Start over":"Börja om", "Drop an image here":"Släpp en bild här", "Choose an image":"Välj en bild", "Paste from clipboard":"Klistra in från urklipp", "Show original":"Visa original", "Replace":"Ersätt", "Output":"Resultat", "Required format":"Obligatoriskt format", "Dimensions":"Mått", "Width":"Bredd", "Height":"Höjd", "Fit":"Anpassa", "Background & transparency":"Bakgrund och transparens", "Quality":"Kvalitet", "Maximum file size":"Maximal filstorlek", "Filename":"Filnamn", "Download optimized image":"Ladda ner optimerad bild", "Privacy":"Integritet", "Local history":"Lokal historik", "Interface language":"Gränssnittsspråk", "Language":"Språk", "Browser default":"Webbläsarens standard", "Back":"Tillbaka" },
    tr: { "Settings":"Ayarlar", "Start over":"Baştan başla", "Drop an image here":"Bir resmi buraya bırakın", "Choose an image":"Resim seç", "Paste from clipboard":"Panodan yapıştır", "Show original":"Orijinali göster", "Replace":"Değiştir", "Output":"Çıktı", "Required format":"Gerekli biçim", "Dimensions":"Boyutlar", "Width":"Genişlik", "Height":"Yükseklik", "Fit":"Sığdır", "Background & transparency":"Arka plan ve saydamlık", "Quality":"Kalite", "Maximum file size":"Maksimum dosya boyutu", "Filename":"Dosya adı", "Download optimized image":"Optimize edilmiş resmi indir", "Privacy":"Gizlilik", "Local history":"Yerel geçmiş", "Interface language":"Arayüz dili", "Language":"Dil", "Browser default":"Tarayıcı varsayılanı", "Back":"Geri" },
    id: { "Settings":"Pengaturan", "Start over":"Mulai lagi", "Drop an image here":"Letakkan gambar di sini", "Choose an image":"Pilih gambar", "Paste from clipboard":"Tempel dari papan klip", "Show original":"Tampilkan asli", "Replace":"Ganti", "Output":"Hasil", "Required format":"Format wajib", "Dimensions":"Dimensi", "Width":"Lebar", "Height":"Tinggi", "Fit":"Sesuaikan", "Background & transparency":"Latar belakang dan transparansi", "Quality":"Kualitas", "Maximum file size":"Ukuran file maksimum", "Filename":"Nama file", "Download optimized image":"Unduh gambar yang dioptimalkan", "Privacy":"Privasi", "Local history":"Riwayat lokal", "Interface language":"Bahasa antarmuka", "Language":"Bahasa", "Browser default":"Bawaan browser", "Back":"Kembali" },
    uk: { "Settings":"Налаштування", "Start over":"Почати знову", "Drop an image here":"Перетягніть зображення сюди", "Choose an image":"Вибрати зображення", "Paste from clipboard":"Вставити з буфера", "Show original":"Показати оригінал", "Replace":"Замінити", "Output":"Результат", "Required format":"Потрібний формат", "Dimensions":"Розміри", "Width":"Ширина", "Height":"Висота", "Fit":"Вписати", "Background & transparency":"Фон і прозорість", "Quality":"Якість", "Maximum file size":"Максимальний розмір файлу", "Filename":"Ім’я файлу", "Download optimized image":"Завантажити оптимізоване зображення", "Privacy":"Конфіденційність", "Local history":"Локальна історія", "Interface language":"Мова інтерфейсу", "Language":"Мова", "Browser default":"Мова браузера", "Back":"Назад" },
    ru: { "Settings":"Настройки", "Start over":"Начать заново", "Drop an image here":"Перетащите изображение сюда", "Choose an image":"Выбрать изображение", "Paste from clipboard":"Вставить из буфера", "Show original":"Показать оригинал", "Replace":"Заменить", "Output":"Результат", "Required format":"Нужный формат", "Dimensions":"Размеры", "Width":"Ширина", "Height":"Высота", "Fit":"Вписать", "Background & transparency":"Фон и прозрачность", "Quality":"Качество", "Maximum file size":"Максимальный размер файла", "Filename":"Имя файла", "Download optimized image":"Скачать оптимизированное изображение", "Privacy":"Конфиденциальность", "Local history":"Локальная история", "Interface language":"Язык интерфейса", "Language":"Язык", "Browser default":"Язык браузера", "Back":"Назад" },
    ar: { "Settings":"الإعدادات", "Start over":"البدء من جديد", "Drop an image here":"أفلت صورة هنا", "Choose an image":"اختر صورة", "Paste from clipboard":"لصق من الحافظة", "Show original":"عرض الأصل", "Replace":"استبدال", "Output":"النتيجة", "Required format":"التنسيق المطلوب", "Dimensions":"الأبعاد", "Width":"العرض", "Height":"الارتفاع", "Fit":"ملاءمة", "Background & transparency":"الخلفية والشفافية", "Quality":"الجودة", "Maximum file size":"الحد الأقصى لحجم الملف", "Filename":"اسم الملف", "Download optimized image":"تنزيل الصورة المحسّنة", "Privacy":"الخصوصية", "Local history":"السجل المحلي", "Interface language":"لغة الواجهة", "Language":"اللغة", "Browser default":"لغة المتصفح", "Back":"رجوع" },
    hi: { "Settings":"सेटिंग", "Start over":"फिर से शुरू करें", "Drop an image here":"चित्र यहाँ छोड़ें", "Choose an image":"चित्र चुनें", "Paste from clipboard":"क्लिपबोर्ड से चिपकाएँ", "Show original":"मूल दिखाएँ", "Replace":"बदलें", "Output":"परिणाम", "Required format":"आवश्यक प्रारूप", "Dimensions":"आयाम", "Width":"चौड़ाई", "Height":"ऊँचाई", "Fit":"फ़िट", "Background & transparency":"पृष्ठभूमि और पारदर्शिता", "Quality":"गुणवत्ता", "Maximum file size":"अधिकतम फ़ाइल आकार", "Filename":"फ़ाइल नाम", "Download optimized image":"अनुकूलित चित्र डाउनलोड करें", "Privacy":"गोपनीयता", "Local history":"स्थानीय इतिहास", "Interface language":"इंटरफ़ेस भाषा", "Language":"भाषा", "Browser default":"ब्राउज़र डिफ़ॉल्ट", "Back":"वापस" },
    th: { "Settings":"การตั้งค่า", "Start over":"เริ่มใหม่", "Drop an image here":"วางรูปภาพที่นี่", "Choose an image":"เลือกรูปภาพ", "Paste from clipboard":"วางจากคลิปบอร์ด", "Show original":"แสดงต้นฉบับ", "Replace":"แทนที่", "Output":"ผลลัพธ์", "Required format":"รูปแบบที่ต้องการ", "Dimensions":"ขนาด", "Width":"ความกว้าง", "Height":"ความสูง", "Fit":"พอดี", "Background & transparency":"พื้นหลังและความโปร่งใส", "Quality":"คุณภาพ", "Maximum file size":"ขนาดไฟล์สูงสุด", "Filename":"ชื่อไฟล์", "Download optimized image":"ดาวน์โหลดรูปที่ปรับแล้ว", "Privacy":"ความเป็นส่วนตัว", "Local history":"ประวัติในเครื่อง", "Interface language":"ภาษาอินเทอร์เฟซ", "Language":"ภาษา", "Browser default":"ค่าเริ่มต้นของเบราว์เซอร์", "Back":"ย้อนกลับ" },
    vi: { "Settings":"Cài đặt", "Start over":"Bắt đầu lại", "Drop an image here":"Thả ảnh vào đây", "Choose an image":"Chọn ảnh", "Paste from clipboard":"Dán từ bộ nhớ tạm", "Show original":"Hiện ảnh gốc", "Replace":"Thay thế", "Output":"Kết quả", "Required format":"Định dạng yêu cầu", "Dimensions":"Kích thước", "Width":"Chiều rộng", "Height":"Chiều cao", "Fit":"Vừa khung", "Background & transparency":"Nền và độ trong suốt", "Quality":"Chất lượng", "Maximum file size":"Kích thước tệp tối đa", "Filename":"Tên tệp", "Download optimized image":"Tải ảnh đã tối ưu", "Privacy":"Quyền riêng tư", "Local history":"Lịch sử cục bộ", "Interface language":"Ngôn ngữ giao diện", "Language":"Ngôn ngữ", "Browser default":"Mặc định trình duyệt", "Back":"Quay lại" },
    ja: { "Settings":"設定", "Start over":"最初からやり直す", "Drop an image here":"ここに画像をドロップ", "Choose an image":"画像を選択", "Paste from clipboard":"クリップボードから貼り付け", "Show original":"元画像を表示", "Replace":"置き換え", "Output":"出力", "Required format":"必要な形式", "Dimensions":"サイズ", "Width":"幅", "Height":"高さ", "Fit":"フィット", "Background & transparency":"背景と透明度", "Quality":"品質", "Maximum file size":"最大ファイルサイズ", "Filename":"ファイル名", "Download optimized image":"最適化画像をダウンロード", "Privacy":"プライバシー", "Local history":"ローカル履歴", "Interface language":"表示言語", "Language":"言語", "Browser default":"ブラウザの既定値", "Back":"戻る" },
    ko: { "Settings":"설정", "Start over":"다시 시작", "Drop an image here":"여기에 이미지를 놓으세요", "Choose an image":"이미지 선택", "Paste from clipboard":"클립보드에서 붙여넣기", "Show original":"원본 보기", "Replace":"바꾸기", "Output":"결과", "Required format":"필수 형식", "Dimensions":"크기", "Width":"너비", "Height":"높이", "Fit":"맞춤", "Background & transparency":"배경 및 투명도", "Quality":"품질", "Maximum file size":"최대 파일 크기", "Filename":"파일 이름", "Download optimized image":"최적화 이미지 다운로드", "Privacy":"개인정보", "Local history":"로컬 기록", "Interface language":"인터페이스 언어", "Language":"언어", "Browser default":"브라우저 기본값", "Back":"뒤로" },
    zh_CN: { "Settings":"设置", "Start over":"重新开始", "Drop an image here":"将图片拖到这里", "Choose an image":"选择图片", "Paste from clipboard":"从剪贴板粘贴", "Show original":"显示原图", "Replace":"替换", "Output":"输出", "Required format":"所需格式", "Dimensions":"尺寸", "Width":"宽度", "Height":"高度", "Fit":"适应", "Background & transparency":"背景和透明度", "Quality":"质量", "Maximum file size":"最大文件大小", "Filename":"文件名", "Download optimized image":"下载优化后的图片", "Privacy":"隐私", "Local history":"本地历史", "Interface language":"界面语言", "Language":"语言", "Browser default":"浏览器默认", "Back":"返回" }
  };
  const { uiLanguage = "browser" } = await chrome.storage.sync.get({ uiLanguage: "browser" });
  const raw = (uiLanguage === "browser" ? chrome.i18n?.getUILanguage?.() : uiLanguage).replace("-", "_") || "en";
  const locale = dictionaries[raw] ? raw : raw.startsWith("pt") ? "pt_BR" : raw.split("_")[0];
  const dictionary = dictionaries[locale] || {};
  const translate = (value) => dictionary[value] || value;
  document.documentElement.lang = locale || "en";
  document.documentElement.dir = locale === "ar" ? "rtl" : "ltr";
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  const nodes = [];
  while (walker.nextNode()) nodes.push(walker.currentNode);
  for (const node of nodes) {
    const trimmed = node.nodeValue.trim();
    if (trimmed && dictionary[trimmed]) node.nodeValue = node.nodeValue.replace(trimmed, dictionary[trimmed]);
  }
  for (const element of document.querySelectorAll("[title],[placeholder],[aria-label]")) {
    for (const attribute of ["title", "placeholder", "aria-label"]) if (element.hasAttribute(attribute)) element.setAttribute(attribute, translate(element.getAttribute(attribute)));
  }
  window.fpTranslate = translate;
})();
